### ISSUE TITLE
DateTime issues

### ISSUE THREAD

**Issue by RobThree** [jaredreich/notie#114]
- [ ] The up/down buttons for date(time?) input are counter-intuitive. When the value is `3` and I click the up-arrow it goes to `2`. Conversely, when the value is `3` and I click the down-arrow it goes to `4`.
- [ ] Also the up-down arrows are a pain when you need to go from, say, 2017 to 1977; that means 40 clicks (especially since holding the mouse button doesn't work either). A way to enter the number would be much better; maybe make the numerical values editable?
- [ ] From the readme:

    > ### Options & Methods
    > ...
    > `dateMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']`

    It's nice that I can specify ('localize') the months, but I can't modify the format? (MDY / DMY / YMD)? Recommended reading: [this](http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time) and [this](http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time)
- [ ] The UI shows MDY but not time; on confirmation it _does_ show a time-part: `You selected: 2017-02-27T15:06:22.836Z` A method to *also* input a time-part would be appreciated; if that's not an option then don't return a time-part (e.g. return `2017-02-27T00:00:00.000Z`)

**Comment by jaredreich** [comment]
Lol, I like your opinionated professor-like demeanour.

#### Buttons:
I don't think everyone would agree that the button position being counter-intuitive. They follow the same flow as the built-in datepicker wheel on iOS (past date above, future date below). I'm sure Apple put some thought into that 😉

#### Large date changes:
I agree with this, and have been considering making the text fields editable. That being said, think about your typical datepicker (with the little calendar popover UI). They ALWAYS start on a nearby date/month and would also take many many clicks to get to 1977.

#### Date format:
Thanks for the "recommended reading", lol. This is pretty edge-case and is likely not worth the LOC involved to allow the user to swap around the date wheels. Just to remind you, this is not a complete date picking library - it's a quick, convenient, and UI friendly way of picking a nearby date (99% of  the time the user will be inputted a nearby date anyways, which just a few clicks away here). If you need a robust datepicker, I'd suggest a different library.

#### Time on output:
That's simply because the datepicker outputs a JavaScript date object. You can do whatever you want with the returned date object. For demonstration purpose, the demo just outputs the date's ISO string (which does show seconds).

**Comment by RobThree** [comment]
> I like your opinionated professor-like demeanour.

I guess I'll take that as a compliment? I just simply pointed out a few issues with notie. It's up to you wether you do something with it.

> They follow the same flow as the built-in datepicker wheel on iOS

A wheel is not up-down arrows? Also: any up-down arrow interface is exactly as I described, not the other way around; example [here](https://jsfiddle.net/RobIII/00vLh5p0/).

> I'm sure Apple put some thought into that 😉

I'm sure too, but I'm also sure you're comparing oranges with apples (pun intended 😛)

> They ALWAYS start on a nearby date/month and would also take many many clicks to get to 1977.

Maybe some? Not the ones I use?

> This is pretty edge-case

A [large part of the world uses D/M/Y](https://en.wikipedia.org/wiki/Date_format_by_country)... I wouldn't call that "pretty edge-case".

>  (99% of the time the user will be inputted a nearby date anyways, which just a few clicks away here)

Assumptions are the mother of... Also: that makes notie pretty opinionated; that is no problem (hey, it's *your* project/library) but if you want more/better adoption then maybe you should consider 'wasting' a few LOC's on these 'edge-cases'. Just my $0.02

> You can do whatever you want with the returned date object

I know; that's besides the point. Point is: user _only_ provided date info, not time-info. So why not _only_ return date info? Why have people remove the time-part themselves when notie can do this easily?

**Comment by jaredreich** [comment]
Closing in favour of #115

**Comment by RobThree** [comment]
> Closing in favour of #115

"sweep valid arguments under rug" you meant to say 😉 

But hey, I donated my $0.02; the rest is up to you. It's _your_ project.

👋

**Comment by jaredreich** [comment]
@RobThree It's your wording buddy, "DateTime Issues", "counter-intuitive", "a pain", "if that's not an option then don't return a time-part". This project doesn't owe you anything, show some respect if you want respect in return. See how to properly file an issue here: https://github.com/jaredreich/notie/issues/112

**Comment by jaredreich** [comment]
> "sweep valid arguments under rug" you meant to say 😉

"Consider one person's strong opinions, then discard them as out of scope" is more like it.

All of this aside, I do appreciate you taking the time to file an issue. You could however work on your people skills my friend!

**Comment by jaredreich** [comment]
First two points are implemented in https://github.com/jaredreich/notie/releases/tag/v4.2.0
I'm going to leave the second two points as out of scope
